const Images = {
  arrow: require('./arrow.png'),
  clearphone: require('./clearphone.png'),
  horsePhone: require('./horse_phone.jpg'),
  horse: require('./horse.jpg'),
  line: require('./line.png'),
  phoneTemplateDark: require('./phone-template-dark-edges.png'),
  phoneTemplateWhite: require('./phone-template-white-edges.png'),
  phoneTemplate: require('./phone-template.png'),
  snakeOne: require('./snake-1.png'),
  snakeTwo: require('./snake-2.png'),
  snakeThree: require('./snake-3.png'),
  thumbnail: require('./thumbnail.png'),
  whatPeopleAreBuying: require('./what-people-are-buying.png'),
  yourImage: require('./your-image.png'),
  testimonialOne: require('./testimonials/1.jpg'),
  testimonialTwo: require('./testimonials/2.jpg'),
  testimonialThree: require('./testimonials/3.jpg'),
  testimonialFour: require('./testimonials/4.jpg'),
  testimonialFive: require('./testimonials/5.jpg'),
  testimonialSix: require('./testimonials/6.jpg'),
  userOne: require('./users/user-1.png'),
  userTwo: require('./users/user-2.png'),
  userThree: require('./users/user-3.png'),
  userFour: require('./users/user-4.jpg'),
  userFive: require('./users/user-5.jpg'),
};

export default Images;
